### ISSUE TITLE
magic in preprocess

### ISSUE THREAD

**Issue by jl1914** [master/nima#2]
In function `preprocess_image`  (nima.py) 
```
image = tf.subtract(image, 0.5)
image = tf.multiply(image, 2.0)
```
I'm confused about the operations, could you give some explanation?
Thanks

**Comment by hcl14** [comment]
I believe it's transformation from range(0,1) to (-1,1). Somewhere above there also must be a step image/255, so that 0..255 values are converted to -1,1.

**Comment by master** [comment]
That @hcl14 said
